#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

#logger "$BUTTON pressed for $SEEN HZ(100)"

_resp_from_wdt_gpio()
{
	echo none > /sys/class/leds/heart/trigger
	echo 0 > /sys/class/leds/heart/brightness
	sleep 1
	echo 1 > /sys/class/leds/heart/brightness
}

_video_ctrl_on_off()
{
	echo $1 > /sys/class/leds/hame:red:gpioctrl/brightness
}

if [ "$SEEN" -eq 6 ]
then
	echo "to connect wifi and start video" > /dev/console
	logger -t BTN_0  "to connect wifi and start video"

	_video_ctrl_on_off 0
	_resp_from_wdt_gpio 1
	/etc/init.d/net4g stop
	#echo timer > /sys/class/leds/heart/trigger
	#echo 300 > /sys/class/leds/heart/delay_on
	#echo 700 > /sys/class/leds/heart/delay_off
	
	pidof ap_client || /usr/bin/ap_client /etc/wifi_up_list
	pidof xmipcnet || /sbin/ipc_renew.sh

elif [ "$SEEN" -eq 18 ]
then
	echo "POWERON video manually" > /dev/console
	logger -t BTN_0  "POWERON video manually"

	_video_ctrl_on_off 0
	_resp_from_wdt_gpio 1
	
elif [ "$SEEN" -eq 24 ]
then
	echo "POWEROFF video automatically" > /dev/console
	logger -t BTN_0 "POWERON video automatically"
	
	_video_ctrl_on_off 1
	_resp_from_wdt_gpio 1
	
elif [ "$SEEN" -gt 55 ]
then
	echo "Default" > /tmp/vcc
	echo "voltage:$SEEN" >> /tmp/vcc
fi

return 0
