#!/bin/sh

# $SEEN has be modifyed at gpio-button.c for VCC detect, 125ms=12.5V
. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 100 ]
	then
		echo "REBOOT" > /dev/console
		sync
		reboot
	elif [ "$SEEN" -ge 500 ]
	then
		echo "RESET WiFi" > /dev/console
		rm -f /etc/config/wireless
		wifi config
		wifi
	elif [ "$SEEN" -ge 10000 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
